### PR TITLE
Fix DiscordRPC (Second attempt)

### LINKED ISSUE #57: Discord RPC not working on steam deck
I am using the flatpak version of Discord and Vinegar.

### PR DESCRIPTION
**Pull request by zzahkaboom24**
Fixes #57 (And this time, hopefully for real)

This is what will make sure the script I am about to upload gets placed in the sandbox properly, I used the patches folder because it made sense to me and all "install" commands in that section targeted some folder in /app/share.

It will run the loop to create the 10 ipc files from [Here](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)#flatpak-applications) now every time the vinegar command is ran, no matter what arguments are being used.

(I also cant think of another or better way of implementing this than that)

### CODE REVIEW

**Comment by zzahkaboom24** [comment]
Drafted by accident because I thought the change did not respect the players choice in the config not to have it, assuming having nothing in the config = an automatic no to discord_rpc. However, upon setting  

[player]  
discord_rpc = false  

it actually stopped working (which is intended), so the PR is open to be merged

**Comment by zzahkaboom24** [comment]
@Thelolguy1 Before I even attempt any merges, I need to ask you a question. How is the --branch option handled in desktop files? Does it somehow work automatically (Because flathubbot makes them as --branch=test), or do you then manually change the branch to stable or similar?

**Comment by zzahkaboom24** [comment]
This is important, because I plan to make a script for this too, but I dont know wether it is somehow handled automatically or not. If its handled manually, the branch wont be changed in the desktop file anymore, but in patches/discordrpc-wrapper/discordrpc-wrapper-desktop.sh

**Comment by zzahkaboom24** [comment]
For your info. With the new approach, it renames the vinegar binary to vinegar-binary and discordrpc-wrapper.sh to vinegar, so the desktop files won't complain. I tested it to work for desktop files; by launching from the roblox website; by launching via commands. Despite this change, technically everything should still be and feel the same.

**Comment by apprehensions** [comment]
Why?

**Comment by apprehensions** [comment]
Is this really required? is it possible to please atleast not use a wrapper?

**Comment by zzahkaboom24** [comment]
I have not found a better way of handling this. If you know a different method I may use, I can go ahead and try it, but without that. I don't think I will be able to achieve this

**Comment by zzahkaboom24** [comment]
Keeping it here if its needed, if its not needed anymore, it can be closed anytime

**Pull request closed without merging**
